### ISSUE TITLE
New Patternfly icons extend outside circles

### ISSUE THREAD

**Issue by spadgett** [kubernetes-ui/topology-graph#17]
The new icons were introduced in v2.9.0.

https://github.com/patternfly/patternfly/releases/tag/v2.9.0

Screenshot:

![screen shot 2016-01-19 at 11 25 55 am](https://cloud.githubusercontent.com/assets/1167259/12431002/0473b7be-bec1-11e5-9b58-9d85ede1d34b.png)

/cc @jwforres @stefwalter

**Comment by abonas** [comment]
@spadgett I was not familiar with the icon changes, but think that the change needs to be done not in the widget, but here:
https://github.com/openshift/origin/blob/master/assets/app/views/project.html#L56
 (and in several other similar lines of code)

I would do the following:
1. increase all radius (the "r" attr) to 18
2. decrease the value of "x" attr for the service
3. if needed, increase/decrease font size for the icons in css (keep in mind that there are icons coming from 2 different font families, so potentially it requires 2 changes -  PatternFlyIcons-webfont and FontAwesome)
cc @rhamilto

**Comment by abonas** [comment]
cc @epwinchell, looks like icon changes are coming with pf 2.9
