### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by naphthalene** [kubernetes-ui/topology-graph#21]
Hello, I'm trying to figure out how to use the JSON data generated by `cluster-insight` in this application (not sure if this is how it fits together). I understand its meant to be a demo, but some docs on this would be useful. Apologies if I'm missing something.

**Comment by somoza** [comment]
There is posible?

**Comment by stefwalter** [comment]
I'm unfamiliar with cluster-insight or what that is. But you can put any data into the topology graph, just adapt it into the required form before updating the graph. See:

https://github.com/kubernetes-ui/topology-graph#usage
