### ISSUE TITLE
Selected node loses its selected indicator when the visibility of its node type is turned off using the legend

### ISSUE THREAD

**Issue by rhamilto** [kubernetes-ui/topology-graph#23]
But if you toggle the visibility of a different node type using the legend, the selected indicator of the selected node returns.

![eghfuul1ci](https://cloud.githubusercontent.com/assets/895728/18451035/68308334-7903-11e6-9ccc-14b534ebd822.gif)

To reproduce:
1. Select a node in the topology graph by clicking it, and note the border of the clicked node is now thicker
2. Turn off and then on the display of the selected node's type by twice clicking its corresponding icon in the legend
3. Note the selected node from step 1 lost its selected indicator (thicker border)
4. Click a different node type in the legend and note the return of the selected indicator on the selected node

I would expect that the selected node retains its selected state indicator until a different node is selected regardless of what happens in the legend.

@stefwalter 

cc:  @jwforres

**Comment by abonas** [comment]
@dclarizio  @serenamarie125 fyi

**Comment by stefwalter** [comment]
@rhamilto Could you test the above pull request and let me know if it does the trick?

**Comment by rhamilto** [comment]
Fixed by #24
