### ISSUE TITLE
Nodes are not selectable in IE11/Edge

### ISSUE THREAD

**Issue by rhamilto** [kubernetes-ui/topology-graph#25]
In testing #24, I noticed that nodes in the graph are not selectable (clickable) in IE11 and Edge.  In other words, if you click a node using one of those browsers, nothing happens.  :(  Note:  this defect exists in both master and #24.

**Comment by stefwalter** [comment]
This is a duplicate bug for https://github.com/d3/d3/pull/2548 I suspect ...
