### ISSUE TITLE
Transclude doesn't work with angular 1.2.4

### ISSUE THREAD

**Issue by abonas** [kubernetes-ui/topology-graph#6]
When using this component with angular 1.2.4, the images in the legend don't show.
The problem is resolved when the following 2 lines are removed from topology-graph.js:
   transclude: true,
   template: "<ng-transclude></ng-transclude>",

When the problem occurs, it looks like this:
![transcludeerr](https://cloud.githubusercontent.com/assets/6277245/8569546/68c8ce18-2581-11e5-9a35-e38a3c6369fd.png)

this branch has angular 1.2.4 and demonstrates the problem:
https://github.com/abonas/topology-graph/tree/checkTransclude

**Comment by abonas** [comment]
this also sounds related:
http://stackoverflow.com/questions/28987880/wrap-directive-content-with-ng-transclude-not-working

**Comment by abonas** [comment]
the following works in angular 1.2.4:
transclude: true,
template: 
`<div ng-transclude></div>`

the difference can be seen here:
https://code.angularjs.org/1.2.4/docs/api/ng.directive:ngTransclude
https://code.angularjs.org/1.3.16/docs/api/ng/directive/ngTransclude

**Comment by stefwalter** [comment]
All the users of this module have moved away from 1.2 ... so unless someone is interested in contributing a fix ... I'm going to close this.
